// Import required packages.
const fs = require('fs');

// Read in the data from the local JSON file that I created.
// This data.json file stores the same data that gets generated by getServerSideProps(...) in `./pages/wcc/leaderboard/index.js`.
let leaderboardData = fs.readFileSync('./python/frozenMNLeaderboard.json', { encoding: 'utf-8' });

// Parse the .json file into a JSON object.
leaderboardData = JSON.parse(leaderboardData);

// Iterate through each user in the private AOC leaderboard.
for (contestant of Object.keys(leaderboardData.props.AOC)) {
  // Iterate through each contestant's completed stars and ensure that they were earned AFTER Sunday, January 1, 2023 12:00:01 AM GMT-06:00.
  for (day of Object.keys(leaderboardData.props.AOC[contestant]['completion_day_level'])) {
    // Iterate through each completed star for each day that contestant completed.
    for (star of Object.keys(leaderboardData.props.AOC[contestant]['completion_day_level'][day])) {
      // If the user completed a star, check that it was completed beofre the deadline of our WCC competition.
      // If the star was completed after, print the contestant's name, AOC Puzzle Number, star from that day, and the timestamp the star was completed.
      if (leaderboardData.props.AOC[contestant]['completion_day_level'][day][star]['get_star_ts'] > 1672552801) {
        console.log(leaderboardData.props.AOC[contestant]['name'], day, star, leaderboardData.props.AOC[contestant]['completion_day_level'][day][star]['get_star_ts']);
      }
    }
  }
}
